### ISSUE TITLE
When delete relationships using Batch API, server error message is not propagated

### ISSUE THREAD

**Issue by ceefour** [neo4j-contrib/java-rest-binding#16]
Client and server in different machines

_Client:_
- Neo4j lib 1.7.2
- Neo4j rest graphdb 1.7
- java version "1.6.0_24"
  OpenJDK Runtime Environment (IcedTea6 1.11.1) (6b24-1.11.1-4ubuntu3)
  OpenJDK Client VM (build 20.0-b12, mixed mode)

_Server:_
- neo4j 1.7.2
- java version "1.7.0_03"
  OpenJDK Runtime Environment (IcedTea7 2.1.1pre) (7~u3-2.1.1~pre1-1ubuntu3)
  OpenJDK Client VM (build 22.0-b10, mixed mode, sharing)

```
15:22:20 [main] DEBUG i.c.b.m.a.RecreatePersonNodesFromLdap - Deleting 26 relationships: [5, 10, 3, 19, 7, 4, 16, 17, 22, 9, 18, 13, 1, 16, 11, 10, 8, 5, 20, 14, 11, 2, 21, 15, 12, 6]
Exception in thread "main" java.lang.RuntimeException: Error recreating Person nodes
        at id.co.bippo.mall.admin.RecreatePersonNodesFromLdap.run(RecreatePersonNodesFromLdap.java:205)
        at id.co.bippo.mall.admin.RecreatePersonNodesFromLdap.main(RecreatePersonNodesFromLdap.java:213)
Caused by: org.neo4j.rest.graphdb.RestResultException:  at
org.neo4j.server.rest.domain.BatchOperationFailedException: 
   org.neo4j.server.rest.web.BatchOperationService.performJob(BatchOperationService.java:176)
   org.neo4j.server.rest.web.BatchOperationService.performBatchOperations(BatchOperationService.java:131)
   sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
   sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.lang.reflect.Method.invoke(Method.java:601)
   com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
   com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
   com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
   com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
   com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
   com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
   com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
   com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
   com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
   com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
   com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
   com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
   com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
   com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
   javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
   org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
   org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
   org.neo4j.server.statistic.StatisticFilter.doFilter(StatisticFilter.java:62)
   org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
   org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
   org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
   org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
   org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
   org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
   org.mortbay.jetty.Server.handle(Server.java:326)
   org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
   org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
   org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
   org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
   org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
   org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
   org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

        at org.neo4j.rest.graphdb.RestAPI.convertRequestResultToEntities(RestAPI.java:232)
        at org.neo4j.rest.graphdb.RestAPI.executeBatch(RestAPI.java:194)
        at id.co.bippo.mall.admin.RecreatePersonNodesFromLdap.run(RecreatePersonNodesFromLdap.java:101)
        ... 1 more
```

**Comment by vishal41190** [comment]
+1
