### ISSUE TITLE
how to use java to exeute cypher through the network?(not embedded)

### ISSUE THREAD

**Issue by myeceptions** [neo4j-contrib/java-rest-binding#78]
GraphDatabaseService db= new RestGraphDatabase("http://xxx.xxx.xxx.xxx:7474/db/data");

ExecutionEngine engine = new ExecutionEngine( db );
ExecutionResult result = engine.execute( "start n = ... match ... where ... return ..." );

------------------------------------------------------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function0
	at org.neo4j.cypher.javacompat.ExecutionEngine.<init>(ExecutionEngine.java:54)
	at org.neo4j.cypher.javacompat.ExecutionEngine.<init>(ExecutionEngine.java:44)
	at test.main(test.java:26)
Caused by: java.lang.ClassNotFoundException: scala.Function0
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

-----------------------------------------------------------------------------------
as above, when i use RestGraphDatabase to initialize ExecutionEngine, some errors occur.
how can i use java to execute cypher throuth the internet?

**Comment by jexp** [comment]
restgraphdatabases.query(statement, params)
